/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "uart_driver.h"
#include "timer_driver.h"
#include "gpio_driver.h"
#include "protocol.h"

/* Forward declaration of our clock function */
void SystemClock_Config(void);

extern volatile uint8_t motor_move_complete_flag;

int main(void)
{
    /* 1. Initialize System base clocks to 84 MHz */
    SystemClock_Config();

    /* 2. Initialize Peripherals */
    UART_Init(115200);
    TIM2_Init();
    TIM3_PWM_Init();

    /* 3. Configure Stepper DIR Pin on PA4 */
    GPIO_PinConfig_t dir_pin = {
        .port  = GPIOA,
        .pin   = 4,
        .mode  = GPIO_MODE_OUTPUT,
        .otype = GPIO_OTYPE_PUSHPULL,
        .speed = GPIO_SPEED_LOW,
        .pull  = GPIO_PULL_NONE
    };
    GPIO_Init(&dir_pin);

    uint8_t raw_buffer[10];
    MoveCommand_t current_command;

    UART_SendString("OpenMotion Core Online (Asynchronous Execution Mode)\r\n");

    /* 4. Infinite Application Lifecycle */
    while (1)
    {
        /* EVENT A: Check if Linux sent a new command packet */
        if (UART_IsMessageReady())
        {
            UART_CopyMessage(raw_buffer);

            if (Protocol_Parse(raw_buffer, &current_command) == 1)
            {
                if (current_command.delay_us == 0)
                {
                    UART_SendByte(ERR_INVALID_PARAMETER);
                }
                else
                {
                    /* Set direction and fire off the hardware timer background engine */
                    GPIO_WritePin(GPIOA, 4, current_command.direction);
                    TIM3_StepperStart(current_command.steps, current_command.delay_us);

                    /* Instantly acknowledge that command is accepted and running */
                    UART_SendByte(STATUS_OK);
                }
            }
            else
            {
                UART_SendByte(ERR_INVALID_COMMAND);
            }
        }

        /* EVENT B: Check if the background motor engine just crossed the finish line */
        if (motor_move_complete_flag == 1)
        {
            /* Reset the flag event so we don't spam messages */
            motor_move_complete_flag = 0;

            /* Notify Linux that the motor is completely still and safe to command again */
            UART_SendByte(STATUS_MOVE_COMPLETE);
        }
    }
}
/*----------------------------------------------------------------
 * SystemClock_Config
 * * Configures the STM32F401RE to run at its maximum 84 MHz speed
 * using the 8 MHz external clock source from the Nucleo ST-LINK.
 *----------------------------------------------------------------*/
void SystemClock_Config(void)
{
    /* 1. Enable the Power Interface Clock to adjust internal core voltage */
    RCC->APB1ENR |= RCC_APB1ENR_PWREN;
    PWR->CR |= PWR_CR_VOS; // Scale 2 mode (Standard for up to 84 MHz)

    /* 2. Turn on the HSE (High-Speed External) clock source */
    RCC->CR |= RCC_CR_HSEON;
    while (!(RCC->CR & RCC_CR_HSERDY)); // Wait until HSE is stable and ready

    /* 3. Configure Flash Memory Wait States (Flash Latency)
     * At 84 MHz, we need 2 Wait States (WS) to prevent flash read timing errors */
    FLASH->ACR = FLASH_ACR_ICEN | FLASH_ACR_DCEN | FLASH_ACR_PRFTEN | FLASH_ACR_LATENCY_2WS;

    /* 4. Configure the Main PLL multipliers and dividers:
     * PLL_M = 8   (8 MHz / 8 = 1 MHz entry)
     * PLL_N = 336 (1 MHz * 336 = 336 MHz VCO)
     * PLL_P = 4   (336 MHz / 4 = 84 MHz System Clock)
     * Source = HSE (1 << 22)
     */
    RCC->PLLCFGR = (8 << 0) | (336 << 6) | (((4 >> 1) - 1) << 16) | RCC_PLLCFGR_PLLSRC_HSE;

    /* 5. Turn on the PLL engine */
    RCC->CR |= RCC_CR_PLLON;
    while (!(RCC->CR & RCC_CR_PLLRDY)); // Wait until PLL is locked and ready

    /* 6. Set bus prescalers (Bridges inside the chip)
     * AHB Prescaler  = 1 (HCLK = 84 MHz)
     * APB1 Prescaler = 2 (PCLK1 = 42 MHz) -> Timers on APB1 will double to 84 MHz!
     * APB2 Prescaler = 1 (PCLK2 = 84 MHz)
     */
    RCC->CFGR |= RCC_CFGR_HPRE_DIV1;
    RCC->CFGR |= RCC_CFGR_PPRE1_DIV2;
    RCC->CFGR |= RCC_CFGR_PPRE2_DIV1;

    /* 7. Switch the main system clock source from original HSI to the new PLL */
    RCC->CFGR &= ~RCC_CFGR_SW;      // Clear bits
    RCC->CFGR |= RCC_CFGR_SW_PLL;   // Select PLL as system clock
    while ((RCC->CFGR & RCC_CFGR_SWS) != RCC_CFGR_SWS_PLL); // Wait for switch confirmation
}
